name: jsigen
description: Generate JavaScript Objects and Bindings in Dart.
version: 0.0.1-placeholder
repository: https://github.com/nikeokoronkwo/dart_catalog

environment:
  sdk: ^3.3.0

executables:
  jsigen:

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  code_builder: ^4.10.0
  logging: ^1.2.0
  node_interop: ^2.1.0
  node_io: ^2.3.0
  path: ^1.9.0
  yaml: ^3.1.2
  yaml_edit: ^2.2.1
  # path: ^1.8.0

dev_dependencies:
  analyzer: ^6.5.0
  build: ^2.4.1
  build_runner: ^2.4.11
  cli_pkg: ^2.10.0
  dart_style: ^2.3.7
  grinder: ^0.9.5
  lints: ^3.0.0
  source_gen: ^1.5.0
  test: ^1.24.0
