name: js_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  analyzer: ^6.8.0
  build: ^2.4.1
  code_builder: ^4.10.1
  dart_style: ^2.3.7
  source_gen: ^1.5.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.13
  lints: ^4.0.0
  test: ^1.24.0
